### ISSUE TITLE
Missing underscore dependency

### ISSUE THREAD

**Issue by johngeorgewright** [spenceralger/gulp-jshint#93]
I get a dependency problem with a fresh install from NPM.

```
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (./node_modules/jshint/src/cli.js:3:25)
    ...
```

**Comment by johngeorgewright** [comment]
Whoa. My bad. Just noticed that's coming from elsewhere. As you were.
